name: contracts

on:
  push:
    branches: [ "main" ]
    paths:
      - 'contracts/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'contracts/*'
env:
  FOUNDRY_PROFILE: ci

jobs:
  check-powervoting-contracts:
    name: hardhat project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Hardhat
        run: |
          cd ./contracts
          yarn install 

      - name: Run Hardhat tests
        run: |
          cd ./contracts
          yarn hardhat test
