name: contracts

on:
  push:
    branches: [ "main" ]
    paths:
      - 'contracts/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'contracts/*'
env:
  FOUNDRY_PROFILE: ci

jobs:
  check-powervoting-contracts:
    name: hardhat project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hardhat
        run: |
          cd ./contracts
          yarn add --dev hardhat@latest typescript

      - name: Run Hardhat tests
        run: |
          cd ./contracts
          yarn hardhat test
