name: contracts

on:
  push:
    branches: [ "main" ]
    paths:
      - 'contracts/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'contracts/*'
env:
  FOUNDRY_PROFILE: ci

jobs:
  check-powervoting-contracts:
    name: hardhat project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd ./contracts
          yarn install --frozen-lockfile 

      - name: Install Hardhat
        run: |
          cd ./contracts
          yarn add --dev @nomicfoundation/hardhat-toolbox @nomicfoundation/hardhat-chai-matchers @nomicfoundation/hardhat-network-helpers @nomicfoundation/hardhat-verify @typechain/ethers-v6 @typechain/hardhat @types/mocha hardhat-gas-reporter solidity-coverage typechain

      - name: Run Hardhat tests
        run: |
          cd ./contracts
          yarn hardhat test
